middleware:
  secret_key: test
aws:
  s3:
    bucket: artifacts
    prefix: media/
  dynamodb:
    table_suffix: local
  cloudfront:
    domain: ${site.artifact_base_url}
site:
  is_test_environment: true
